### ISSUE TITLE
Hacker News Submission

### ISSUE THREAD

**Issue by nikolay** [TekWizely/bingo#1]
Hi! I decided to bring some awareness to the project and submitted it here: https://news.ycombinator.com/item?id=29690251

**Comment by TekWizely** [comment]
Hey thanks so much for the call out - was on xmas vacay so missed my chance to participate early in the post, but will be reading over and posting.

Glad you enjoy Bingo - Thanks again and Happy Holidays !

**Comment by TekWizely** [comment]
Its been over 24 hours without any new stars, so I think we can call this bump-run over.

It was good for 140 stars to the repo, so thank you very much for taking the time to post!
